function mdh=defMDH11()
    mdh.flags=int32(0); % ulFlagsAndDMALength
    mdh.measuid=int32(0); % lMeasUID
    mdh.scancntr=int32(0);% ulScanCounter
    mdh.timestamp=int32(0); % ulTimeStamp                   
    mdh.pmutime=int32(0); % ulPMUTimeStamp
    mdh.systime=int16(0); % ushSystemType
    mdh.ptabdelay=int16(0); % ulPTABPosDelay
    mdh.ptabpos=zeros(3,1,'int32'); % absolute PTAB position in [µm] x,y,z
    mdh.reserve=int32(0);
    mdh.evalmask=zeros(2,1,'int32'); % aulEvalInfoMask[MDH_NUMBEROFEVALINFOMASK] 
    mdh.samples=int16(0); % ushSamplesInScan              
    mdh.channels=int16(0); % ushUsedChannels     
    mdh.loopcnts=zeros(14,1,'int16'); % sLoopCounter sLC
    mdh.cutoff=zeros(2,1,'int16'); % sCutOffData sCutOff
    mdh.ksccol=int16(0); % ushKSpaceCentreColumn         
    mdh.coilsel=int16(0); % ushCoilSelect                 
    mdh.ro_off=single(0); % fReadOutOffcentre             
    mdh.lasstrf=int32(0); % ulTimeSinceLastRF             
    mdh.kscline=int16(0); % ushKSpaceCentreLineNo         
    mdh.kscpart=int16(0); % ushKSpaceCentrePartitionNo    
    mdh.slicedat=zeros(7,1,'single'); % Slice Data: flSag flCor flTra aflQuaternion[4]
    mdh.te=single(0.0); % aushIceProgramPara[0,1]
    mdh.ky=int16(0); % aushIceProgramPara[2]
    mdh.kz=int16(0);% aushIceProgramPara[3]
    mdh.ramp=int16(0); % aushIceProgramPara[4]
    mdh.flat=int16(0); % aushIceProgramPara[5] 
    mdh.rsamptime=int16(0); % aushIceProgramPara[6]
    mdh.tsp=int16(0); % aushIceProgramPara[7]
    mdh.icefree=zeros(16,1,'int16'); % free parameter for IceProgram
    mdh.res_par=zeros(4,1,'int16'); % reserved parameters
    mdh.app_cnt=int16(0);
    mdh.app_mask=int16(0);
    mdh.crc=int32(0);  % RC 32 checksum
end